Node Version Update to 18 (#3850)
* Update to node version 18. Resolve error with package @achrinza/node-ipc. Use temp workaround openssl.cnf to bypass unsafe legacy renegotiation error

Signed-off-by: HenryXiaoHX <hxiao@ucsd.edu>

* debug commit

* update packages in warnings to latest versions

Signed-off-by: HenryXiaoHX <hxiao@ucsd.edu>

* debug commit for typescript error

Signed-off-by: HenryXiaoHX <hxiao@ucsd.edu>

* revert to resolve maximum range exceeded error
next step: resolve type errors

* temporarily work around error
"Type 'undefined' is not assignable to type 'string'

* fix type errors

Signed-off-by: HenryXiaoHX <hxiao@ucsd.edu>

* fix webpack/polyfill errors

Signed-off-by: HenryXiaoHX <hxiao@ucsd.edu>

* resolve error 'components','validations','mixins' does not exist'

Signed-off-by: HenryXiaoHX <hxiao@ucsd.edu>

* solve error '' does not exist on type

Signed-off-by: HenryXiaoHX <hxiao@ucsd.edu>

* fix more type errors

Signed-off-by: HenryXiaoHX <hxiao@ucsd.edu>

* run lint

* resolve webpack unmet peer dependency. include only necessary plugin

Signed-off-by: HenryXiaoHX <hxiao@ucsd.edu>

* resolve error cannot read "prototype" in sax.js with patch

* resolve error Class extends value undefined is not a constructor, in async-csv

Signed-off-by: HenryXiaoHX <hxiao@ucsd.edu>

* resolve error 'cannot read properties of undefined (reading '1')' for Prismjs

Signed-off-by: HenryXiaoHX <hxiao@ucsd.edu>

* run prettier, update engine requirement

Signed-off-by: HenryXiaoHX <hxiao@ucsd.edu>

* change workflow to test node 18

* resolve error: updateNodeVersionTo18

* resolve error patch-package not found

* resolve error "unknown file extension '.ts'"

* resolve error 'Argument of type 'unknown' is not assignable to parameter to type 'string | undefined'

* try to resolve ts file extension not recognized

* try to resolve unknown ts extension

* try out commonjs, solution 1

* try solution 2

* solve cannot find module '@/views/Compare.vue'

* inspecjs won't run without module resolution

* Revert "resolve error "unknown file extension '.ts'""

This reverts commit b472dab242eb701352c1f80d5cb7affd9110468f.

* fixes for frontend test, hdf-converters test

* resolve unknown file extension ts

* resolve "index signature for type 'number' is missing'

* resolve missing basic DOM types

* Temporary solution for linting

* update cypress version

* Attempt fix in pr(add api key to groups) for cypress

* Attempt fix in pr, for cypress

* adopt type fixes in pr and see if cypress is ok

* remove unused variable for linting

* expriment with nonstrict typescript

* revert to use strict mode

* experiment with uncaught exception

* experiment with uncaught exception in index file

* experiment with cypress wait time

* experiment with cypress wait config

* add yarn lock file

* experimnet with longer wait time becuase longest time is 24042 in last run

* remove shim file (test for correct import), update prism regex

* experiment with shim files, run lint

* get rid of irrevelant wait time, include quotes

* change to async method

* try to use registrationPage as opposed to cy.register

* visit signup (in beforeeach in registration page_

* put async in beforeeach

* revert last commit, add async in register command

* revert async. use id, not attribute for selection

* test form is present first

* Revert "experimnet with longer wait time becuase longest time is 24042 in last run"

This reverts commit 764f3bc7e3f05ae0ae2b0d48c94483a4be5baa7b.

* change to large wait time to rule out timing error

* revert wait time, try async in registration

* experiment with no registering in beforeach

* this worked on login tests

* Temporary workaround: revisit later

* longer wait time to remove time uncertainty

* 1. revert workflows to test main branch 2. include supported node range
3. revert docker to use lts

* root level tsconfig seems to be not passed it

* disable alwaysStrict

* remove workaround

* disable alwaysStrict

* don't implicit use strict

* babel option remove strict

* fix syntax for babel preset

* add sourcetype as script

* should be failing becuase of the libraries in node_modules

* revert back to removing workaround

* experiment and see if top level was not correctly extended

* experiment with plugin to remove use strict

* revert last commit, experiment different plugin

* remove strcit mode with custom script

* Ignore node_modules. Revert "remove strcit mode with custom script"

This reverts commit abc90493e16803ace8c38461633f45b6dd56b51d.

* skip lib check

* try es2022

* change type to commonjs

* revert changes in babel loader

* fix error no inputs were found in config

* experiment with allownull

* missed one allow null

* experiment with tsconfig

* Revert "try es2022"

This reverts commit b99e7b676e71ed464af392f66d7f89fe5a5fb63f.

* resolve peer dependency warning babel-loader

* custom script (fix path not found) remove strict

* update fs syntax

* experiment with jquery import

* hard code version (not use fs) for jquery

* Revert "update fs syntax", "experiment with jquery import" "hard code version"

* node polyfill fs

* experiment with removing jquery

* experiment with taking jquery/bootstrap out

* exclude public static folder in webpack tsconfig

* missing installations babel-loader and babel/preset-env

* fix type error and cypress

* exclude jquery with externals

* use transform-remove-strict-mode plugin

* use preset 'env' as opposed to '@babel/preset-env'

* convert into commonjs module

* yarn.lock update

Signed-off-by: Charles Hu <chu@mitre.org>

* Deconflict Cypress test updates

Signed-off-by: Charles Hu <chu@mitre.org>

* Revert "Deconflict Cypress test updates"

This reverts commit d8555d3197311e58b370273fa2f49f996039c15b.

t Please enter the commit message for your changes. Lines starting

* Fix merge w/ master

* Deconflict integration test

Signed-off-by: Charles Hu <chu@mitre.org>

* Deconflict HTML export

Signed-off-by: Charles Hu <chu@mitre.org>

* Deconflict HTML export 2

Signed-off-by: Charles Hu <chu@mitre.org>

* Remove patch

Signed-off-by: Charles Hu <chu@mitre.org>

* Node version change

Signed-off-by: Charles Hu <chu@mitre.org>

* Reverted groups change

Signed-off-by: Charles Hu <chu@mitre.org>

* Unifying package.jsons

Signed-off-by: Charles Hu <chu@mitre.org>

* Node versioning

Signed-off-by: Charles Hu <chu@mitre.org>

* Node versioning

Signed-off-by: Charles Hu <chu@mitre.org>

* Node versioning

Signed-off-by: Charles Hu <chu@mitre.org>

* Node versioning

Signed-off-by: Charles Hu <chu@mitre.org>

* Remove deprecated compiler option

Signed-off-by: Charles Hu <chu@mitre.org>

* Update GH workflow files

Signed-off-by: Charles Hu <chu@mitre.org>

* Removing component class declarations

Signed-off-by: Charles Hu <chu@mitre.org>

* Revert mapper changes

Signed-off-by: Charles Hu <chu@mitre.org>

* Base converter changes

Signed-off-by: Charles Hu <chu@mitre.org>

* Linting; revert xml2json changes

Signed-off-by: Charles Hu <chu@mitre.org>

* Remove SSL manipulation

Signed-off-by: Charles Hu <chu@mitre.org>

* Revert "Remove SSL manipulation"

This reverts commit d9eccd131717d7ef381fd004b468563b6d206aeb.

* Test compiler config change

Signed-off-by: Charles Hu <chu@mitre.org>

* Revert high level tsconfig changes

Signed-off-by: Charles Hu <chu@mitre.org>

* Netlify config file

Signed-off-by: Charles Hu <chu@mitre.org>

* Netlify config file

Signed-off-by: Charles Hu <chu@mitre.org>

* Alternative node version specifier

Signed-off-by: Charles Hu <chu@mitre.org>

* Revert version specification

Signed-off-by: Charles Hu <chu@mitre.org>

* Netlify config file

Signed-off-by: Charles Hu <chu@mitre.org>

* Remove netlify config file

Signed-off-by: Charles Hu <chu@mitre.org>

* Node version specifier

Signed-off-by: Charles Hu <chu@mitre.org>

* Dependency updates

Signed-off-by: Charles Hu <chu@mitre.org>

* Revert tsconfig change

Signed-off-by: Charles Hu <chu@mitre.org>

* Apps package.json change

Signed-off-by: Charles Hu <chu@mitre.org>

* Modal change revert

Signed-off-by: Charles Hu <chu@mitre.org>

* Value fix

Signed-off-by: Charles Hu <chu@mitre.org>

* yarn.lock change

Signed-off-by: Charles Hu <chu@mitre.org>

* Test strict avoidance on package

Signed-off-by: Charles Hu <chu@mitre.org>

* Strict test

Signed-off-by: Charles Hu <chu@mitre.org>

* Fixed vue config errors

Signed-off-by: Charles Hu <chu@mitre.org>

* Jsonix update

Signed-off-by: Charles Hu <chu@mitre.org>

* Yarn lock update

Signed-off-by: Charles Hu <chu@mitre.org>

* NestJS update

Signed-off-by: Charles Hu <chu@mitre.org>

* CSV lib change

Signed-off-by: Charles Hu <chu@mitre.org>

* CSV lib change

Signed-off-by: Charles Hu <chu@mitre.org>

* Revert "CSV lib change"

This reverts commit b275134541aa29927bbac3a9c0a7aba1153d3ce7.

* Revert "CSV lib change"

This reverts commit b3d6507be4e0177163d48efc62d67baf518eb3d2.

* Temp removal of csv lib

Signed-off-by: Charles Hu <chu@mitre.org>

* Test shim removal in test

Signed-off-by: Charles Hu <chu@mitre.org>

* Revert shim changes

Signed-off-by: Charles Hu <chu@mitre.org>

* Test frontend shim change

Signed-off-by: Charles Hu <chu@mitre.org>

* Test stripStrict deletion

Signed-off-by: Charles Hu <chu@mitre.org>

* Test eslint changes

Signed-off-by: Charles Hu <chu@mitre.org>

* CSV lib replacement

Signed-off-by: Charles Hu <chu@mitre.org>

* Linting

Signed-off-by: Charles Hu <chu@mitre.org>

* Process.env fix, jest module finding fix

Signed-off-by: Charles Hu <chu@mitre.org>

* Jest config changes

Signed-off-by: Charles Hu <chu@mitre.org>

* Fixed CSV generation missing headers

Signed-off-by: Charles Hu <chu@mitre.org>

* Update ExportCSVModal.vue

* Minor changes

Signed-off-by: Charles Hu <chu@mitre.org>

* Added axios to backend dependencies

Signed-off-by: Charles Hu <chu@mitre.org>

* update yarnlock and try out using the clipboard api directly since it's no longer finding the exports for v-clipboard for some bizzaro world reason

Signed-off-by: Amndeep Singh Mann <amann@mitre.org>

* I think this was something that was up with Henry's system where he was dealing with some openssl issues

Signed-off-by: Amndeep Singh Mann <amann@mitre.org>

* updated dockerfiles to use node18

Signed-off-by: Amndeep Singh Mann <amann@mitre.org>

* updated workflow runners to ubuntu 22.04

Signed-off-by: Amndeep Singh Mann <amann@mitre.org>

* try re-enabling production on everything

Signed-off-by: Amndeep Singh Mann <amann@mitre.org>

---------

Signed-off-by: HenryXiaoHX <hxiao@ucsd.edu>
Signed-off-by: Charles Hu <chu@mitre.org>
Signed-off-by: Amndeep Singh Mann <amann@mitre.org>
Co-authored-by: HenryXiaoHX <hxiao@ucsd.edu>
Co-authored-by: Charles Hu <chu@mitre.org>
Co-authored-by: Charles Hu <106095667+charleshu-8@users.noreply.github.com>
Co-authored-by: Amndeep Singh Mann <amann@mitre.org>